---
# Model configuration
model_name: "ban_student/resnet50_32x4d"
backbone: "custom_resnet50_32x4d"
num_classes: 6
pretrained: true
batch_size: 16
stochastic_depth_prob: 0.8

# Student configuration
generation: 3

# Teacher configuration
teacher_list: "checkpoint/resnet50_32x4d_teacher/radboud/epoch=14.ckpt"
label_type: "hard"

# Sample configuration
sample: "downsample"

# Loss function
loss_func: "ban_loss_func"
coeff: 1.
anneal_type: false
temperature: 0.8

# Transformation
difficulty: [20, 20, 20]
student_transformation: student_transformation
train_transformation: null
test_transformation: null

# optimizer config
optimizer_type: "Over9000"
max_lr: 0.04
base_momentum: 0.85
max_momentum: 0.9
nestrov: false
weight_decay: 0.00005

# scheduler config
scheduler_type: "1cycle"
warmup: 0
cool_down: 0
total_epoch: 0


# Other parameters
dropout: 0.4
data_dir: "normalized_train12x128x128"