---
# Model configuration
model_name: "wide_resnet50_2_ban_student"
backbone: "custom_wide_resnet50_2"
num_classes: 6
pretrained: true
batch_size: 20
stochastic_depth_prob: 0.8

# Student configuration
generation: 3

# Teacher configuration
teacher_list: "checkpoint/resnet50_32x4d_teacher/radboud/epoch=14.ckpt"
label_type: "soft"

# Loss function
loss_func: "ban_loss_func"
coeff: 1.0
anneal_type: true
temperature: 1.0

# Transformation
difficulty: [7, 15, 20]
student_transformation: student_transformation
train_transformation: null
test_transformation: null

# optimizer config
optimizer_type: "SGD"
max_lr: 0.04
base_momentum: 0.85
max_momentum: 0.9
nestrov: false
weight_decay: 0.00005

# scheduler config
scheduler_type: "1cycle"
warmup: 0
cool_down: 0
num_cycle: 4
epoch_per_cycle: 5


# Other parameters
dropout: 0.4
data_dir: "train12x128x128"