---
# Model configuration
model_name: "resnet50_32x4d_teacher"
backbone: "resnet50_32x4d"
num_classes: 6
pretrained: true
batch_size: 16

# Loss function
loss_func: "crossentropy"

# Transformation
train_transformation: standard_transforms
test_transformation: null

# optimizer config
optimizer_type: "SGD"
max_lr: 0.01
base_momentum: 0.85
max_momentum: 0.9
nestrov: false
weight_decay: 0.00005

# scheduler config
scheduler_type: "1cycle"
warmup: 0
cool_down: 0
num_cycle: 3
epoch_per_cycle: 5


# Other parameters
dropout: 0.4
data_dir: "train16x128x128"