---
# Model configuration
model_name: "outliers/resnet18"
backbone: "custom_resnet18"
num_classes: 6
pretrained: true
batch_size: 16
stochastic_depth_prob: 0.8

# Teacher configuration
teacher_list: "checkpoint/baseline/resnet50/version3/epoch=14.ckpt"
label_type: "soft"
keep_classes: 2

# Sample configuration
sample: "downsample"

# Loss function
loss_func: "outliers_loss_func"
coeff: 0.1
anneal_type: false
temperature: 1.0

# Transformation
student_aug: student_transformation
teacher_aug: standard_transforms
test_aug: standard_transforms
train_aug: null

# optimizer config
optimizer_type: "Over9000"
max_lr: 0.005
base_momentum: 0.9
max_momentum: 0.95
nestrov: false
weight_decay: 0.00005

# scheduler config
scheduler_type: "1cycle"
warmup: 0
cool_down: 0
total_epoch: 100


# Other parameters
data_dir: "train12x128x128"