---
# Model configuration
model_name: "baseline/resnet50_32x4d"
backbone: "resnet50_32x4d"
num_classes: 6
pretrained: true
batch_size: 16

# Data method
sample: "downsample"

# Loss function
loss_func: "crossentropy"
temperature: 1.2

# Transformation
train_transformation: standard_transforms
test_transformation: null

# optimizer config
optimizer_type: "Over9000"
max_lr: 0.01
base_momentum: 0.85
max_momentum: 0.9
nestrov: false
weight_decay: 0.00005

# scheduler config
scheduler_type: "1cycle"
total_epoch: 15
cool_down: 0
warmup: 0

# Other parameters
dropout: 0.4
data_dir: "normalized_train12x128x128"