---
# Model configuration
model_name: "baseline/resnet50"
backbone: "resnet50"
num_classes: 6
pretrained: true
batch_size: 16

# Data method
sample: "downsample"

# Loss function
loss_func: "crossentropy"
temperature: 1.0

# Transformation
train_aug: standard_transforms
test_aug: standard_transforms

# optimizer config
optimizer_type: "Over9000"
max_lr: 0.01
base_momentum: 0.85
max_momentum: 0.9
nestrov: false
weight_decay: 0.00005

# scheduler config
scheduler_type: "1cycle"
total_epoch: 15
cool_down: 0
warmup: 0

# Other parameters
dropout: 0.4
data_dir: "train12x128x128"
fix_res: "train12x224x224"