---
# Model configuration
model_name: "student_multi/efficientnet-b0"
backbone: "efficientnet-b0"
num_classes: 6
pretrained: true
batch_size: 16
val_batch_size: 20
stochastic_depth_prob: 0.8

# Teacher configuration
label_type: "soft"
loss_type: "crossentropy"

# Sample configuration
sample: "upsample"

# Loss function
loss_func: "bam_loss_func"
coeff: 1.
anneal_type: true
temperature: 1.
split_batch_norm: true

# Transformation
train_aug: standard_transforms
test_aug: standard_transforms

# optimizer config
optimizer_type: "Over9000"
max_lr: 0.0008
decay_layer: 0.9
base_momentum: 0.85
max_momentum: 0.9
nestrov: false
weight_decay: 0.00005

# scheduler config
layer_wise: true
scheduler_type: "warmup_cosine"
warmup: 5
cool_down: 0
total_epoch: 20


# Other parameters
data_dir: "train16x128x128"